name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          record: true
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ 86d83402-8e39-44b0-b47f-09ee167dedc7 }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}